version: 2
updates:

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"

    reviewers: [ "qianjunakasumi" ]
    assignees: [ "qianjunakasumi" ]
    open-pull-requests-limit: 114
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore:arrow_up:cargo "

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

    reviewers: [ "qianjunakasumi" ]
    assignees: [ "qianjunakasumi" ]
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore:arrow_up:actions "
