version: 2
updates:

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"

    reviewers: [ "qianjunakasumi" ]
    assignees: [ "qianjunakasumi" ]
    open-pull-requests-limit: 114
    rebase-strategy: "disabled"
    commit-message:
      prefix: "pref⬆️cargo "

  - package-ecosystem: "gomod"
    directory: "/src/network/protocol/jce/generator"
    schedule:
      interval: "daily"

    reviewers: [ "qianjunaka`sumi" ]
    assignees: [ "qianjunakasumi" ]
    open-pull-requests-limit: 114
    rebase-strategy: "disabled"
    commit-message:
      prefix: "pref⬆️gomod "

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

    reviewers: [ "qianjunakasumi" ]
    assignees: [ "qianjunakasumi" ]
    open-pull-requests-limit: 114
    rebase-strategy: "disabled"
    commit-message:
      prefix: "pref⬆️action "

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"

    reviewers: [ "qianjunakasumi" ]
    assignees: [ "qianjunakasumi" ]
    open-pull-requests-limit: 114
    rebase-strategy: "disabled"
    commit-message:
      prefix: "pref⬆️gitsubmodule "
