// This file is automatically @generated by JceGenerator.
// It is not intended for manual editing.

use bytes::{Bytes, BytesMut};

use conch_jce::{JceReader, JceWriter};
use conch_jce::field::{JBool, JByte, JceStruct, JDouble, JFloat, JInt, JList, JLong, JMap, JShort, JSList, JString};

////////////////////////////////////////////////////////////////////////////////

#[derive(Default)]
pub struct HttpServerListReq {
    pub a: JLong,
    pub b: JLong,
    pub c: JByte,
    pub d: JString,
    pub e: JInt,
    pub f: JLong,
    pub g: JString,
}

impl JceStruct for HttpServerListReq {
    fn s_to_bytes(&self, b: &mut BytesMut) {
        let mut w = JceWriter::new(1);
        w.put(&self.a);
        w.put(&self.b);
        w.put(&self.c);
        w.put(&self.d);
        w.put(&self.e);
        w.put(&self.f);
        w.put(&self.g);
        w.flash(b);
    }

    fn s_from_bytes(&mut self, b: &mut Bytes) {
        let mut r = JceReader::with_tag(b, 1);
        self.a = r.get();
        self.b = r.get();
        self.c = r.get();
        self.d = r.get();
        self.e = r.get();
        self.f = r.get();
        self.g = r.get();
    }
}