// This file is automatically @generated by JceGenerator.
// It is not intended for manual editing.

use bytes::{Bytes, BytesMut};

use jce::{JceReader, JceWriter};
use jce::field::{JBool, JByte, JceStruct, JDouble, JFloat, JInt, JList, JLong, JMap, JShort, JSList, JString};

////////////////////////////////////////////////////////////////////////////////

#[derive(Default)]
pub struct HttpServerListReq {
    pub uin: JLong,
    pub timeout: JLong,
    pub c: JByte,
    pub imsi: JString,
    pub is_wifi_conn: JInt,
    pub app_id: JLong,
    pub imei: JString,
}

impl JceStruct for HttpServerListReq {
    fn s_to_bytes(&self, b: &mut BytesMut) {
        let mut w = JceWriter::new(1);
        w.put(&self.uin);
        w.put(&self.timeout);
        w.put(&self.c);
        w.put(&self.imsi);
        w.put(&self.is_wifi_conn);
        w.put(&self.app_id);
        w.put(&self.imei);
        w.flash(b);
    }

    fn s_from_bytes(&mut self, b: &mut Bytes) {
        let mut r = JceReader::with_tag(b, 1);
        self.uin = r.get();
        self.timeout = r.get();
        self.c = r.get();
        self.imsi = r.get();
        self.is_wifi_conn = r.get();
        self.app_id = r.get();
        self.imei = r.get();
    }
}