[package]
name = "cookie-jce"
version = "1.0.0"
edition = "2021"

[lib]
path = "lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.5.0"
rustc-hash = "1.1.0"
tracing = "0.1.37"
