name: Cargo Update

on:
  schedule:
    - cron: '0 1 * * 3'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: tibdex/github-app-token@v1
        name: Generate token
        id: generate-token
        with:
          app_id: 242446
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Update
        run: cargo update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: pref⬆️cargo update lock file
          signoff: true
          branch: pref/cargo-update
          delete-branch: true
          title: pref⬆️cargo update lock file
          body: |
            Update cargo lock file.
