name: Release testing channel

on:
  push:
    branches: [ "main" ]
    paths: [ "**.rs", "dashboard/src/**", ".github/workflows/release-testing-channel" ]

  workflow_dispatch:

jobs:

  build:
    name: Build product and upload
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Dashboard
        run: |
          cd dashboard
          npm install -g pnpm
          npm install -g @quasar/cli
          pnpm i
          quasar build

      - name: Install Rust Beta
        run: |
          rustup toolchain install beta --profile minimal
          rustup default beta    

      - name: Setup Protoc
        uses: Noelware/setup-protoc@1.0.2

      - name: Cache Crates
        uses: actions/cache@v3
        with:
          path: |
            ./target
            ~/.cargo
          key: conch-testing-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            conch-testing-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}   

      - name: Build Conch
        run: cargo build --bin conch --release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/project-senjuko/conch:testing
